### ISSUE TITLE
Causing heavy FPS drops in Girls & Chainsaw.

### ISSUE THREAD

**Issue by RedAISkye** [ManlyMarco/UniversalUnityDemosaics#1]
It successfully de-censors the game "**[Girls & Chainsaw](https://www.dlsite.com/maniax/work/=/product_id/RJ402432.html)**" but causes heavy FPS drops.

Without the plugin, the game runs smooth.

**Comment by ManlyMarco** [comment]
Only use one of the plugins at a time. Most of these plugins are pretty dumb as specified in the names and will search for mozaics on every frame, possibly visibly affecting performance. This isn't really a bug, the game will just need a more tailored solution.

**Comment by RedAISkye** [comment]
> Only use one of the plugins at a time.
I am using only one plugin called "DumbRendererDemosaicIl2Cpp.dll" with the latest BepInEx v6 build.

> will search for mozaics on every frame, possibly visibly affecting performance.
Is it possible to manually remove it then?
I usually snoop around with dnSpy but can't do that for il2cpp.

**Comment by ManlyMarco** [comment]
Remove what, the mozaic? You can probably use the UnityExplorer plugin, not sure how good it is at manipulating materials. Check log to see what renderers the dumb demosaic is disabling and have a go at it.
