### ISSUE TITLE
BepInEx6_IL2CPP_v1.5 can't be loaded by RJ01062825 using BepInEx #672 & #668

### ISSUE THREAD

**Issue by xuqixuan0212** [ManlyMarco/UniversalUnityDemosaics#3]

**Comment by ManlyMarco** [comment]
The plugin is built for https://github.com/BepInEx/BepInEx/releases/tag/v6.0.0-pre.1

**Comment by EricZhou05** [comment]
> The plugin is built for https://github.com/BepInEx/BepInEx/releases/tag/v6.0.0-pre.1

For the game I'm playing, BepInEx 6.0.0-pre.1 cannot be installed. However, the BepInEx Bleeding Edge version (Be.682) can be installed, but it fails to load UniversalUnityDemosaics_BepInEx6_IL2CPP_v1.5. Is there a UniversalUnityDemosaics.dll that supports the BepInEx Bleeding Edge version?

**Comment by ManlyMarco** [comment]
Check the releases.

**Comment by EricZhou05** [comment]
Thank you very much, it works!!!

**Comment by EricZhou05** [comment]
> Check the releases.

Thank you very much, it works!!!
