### ISSUE TITLE
Regarding the red text appearing in Logging.Console

### ISSUE THREAD

**Issue by CheerChee** [ManlyMarco/UniversalUnityDemosaics#4]
After turning on Logging.Console, an error message appears, and the plugin is invalid. Although I don’t know where to put the plugin, I have opened a plugin folder and put the plugin in it.

![螢幕擷取畫面 2024-03-25 140615](https://github.com/ManlyMarco/UniversalUnityDemosaics/assets/164301925/2bf7ff9d-c20b-44da-8148-e8a2f7735ae5)
![螢幕擷取畫面 2024-03-25 140636](https://github.com/ManlyMarco/UniversalUnityDemosaics/assets/164301925/afe19e2c-5d07-4d1d-8984-e22c18772374)

**Comment by ManlyMarco** [comment]
Use latest version of BepInEx6 with corresponding updated demosaic dll.

**Comment by CheerChee** [comment]
> 使用最新版本的 BepInEx6 以及相應更新的 demosaic dll，pre1 到目前為止已經很舊並且存在已知問題。

But I just use the latest version 6.0.0-pre.1. Because the game uses il2cpp, I can only use this version. In addition, demosaic dll also uses pre6. I checked that the version I am using is the latest version.

**Comment by ManlyMarco** [comment]
6.0.0-pre.1 is not the latest version, you can find the latest builds [here](https://builds.bepinex.dev/projects/bepinex_be).
