### ISSUE TITLE
用了DumbRendererDemosaic_Il2Cpp_net6掉帧

### ISSUE THREAD

**Issue by Shirakawa-Zhang** [ManlyMarco/UniversalUnityDemosaics#5]
感谢大佬分享去码方法，之前很多都成功了。今天遇到了大问题，BepInEx的版本是x64的688，命令行能启动，也能读取插件，就是加载Demosaic.dll进游戏地图后会掉帧，游戏是三月29日发售的 地下城の女騎士。
这个有什么好的解决方法嘛，之前也有别的游戏轻微掉帧，但是这个从加载Demosaic.dll之后不仅没有去码而且从本来的100多帧降到了个位数，是版本版本问题吗？
大概的原因也好，有空大佬理我一下！

**Comment by ManlyMarco** [comment]
In order to work in as many games as possible, the plugin is very unoptimized. The performance hit will vary between different games and isn't easily fixed while keeping high compatibility.

The best way to fix this would be to create a modified version of the demosaic plugin for that particular game.

**Comment by Shirakawa-Zhang** [comment]
Thanks for comment, I see. 
BTW, is it easy to create it ?  
Or can the game be demosaicked with other methods like the blog you wrote ?

**Comment by ManlyMarco** [comment]
Since it's an IL2CPP game it will be a bit more difficult but it shouldn't be too hard to modify the existing demosaic to work better in that particular game. It would just need a bunch of trial and error to see what works.

**Comment by Shirakawa-Zhang** [comment]
Could you tell me what I can do or write something as a tutorial in your blog? I know nothing about it but I would have a try by myself. It may take some of your time...

**Comment by ManlyMarco** [comment]
It's all fairly standard Unity engine programming, guides for C# and Unity apply here for the most part (IL2CPP complicates this quite a bit however, you might need to look information and help on the BepInEx discord server). Here's a guide for making a plugin itself http://docs.bepinex.dev/master/articles/index.html though most of it is already done if you use the existing plugin as a base.
